version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:17.06.0-ce-git
        environment:
          IMAGE_NAME: "sameersbn/squid"

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce

      - run:
          name: Docker info
          command: |
            docker version
            docker info

      - restore_cache:
          keys:
            - cache-{{ .Branch }}
          paths:
            - /cache/layers.tar

      - run:
          name: Loading docker cache
          command: |
            if [[ -f /cache/layers.tar ]]; then
              docker load -i /cache/layers.tar
            fi

      - run:
          name: Build docker image
          command: |
            docker build --cache-from=${IMAGE_NAME} -t ${IMAGE_NAME} .

      - run:
          name: Launching container for testing
          command: |
            docker network create testnet
            docker run --name squid-cache -d --net testnet -p 3128:3128 $IMAGE_NAME
            sleep 5

      - run:
          name: Testing image
          command: |
            docker run --rm --net testnet appropriate/curl --retry 3 --retry-delay 5 -vL -x http://squid-cache:3128 https://www.google.com

      - run:
          name: Generate docker build image cache
          command: |
            mkdir -p /cache
            docker save -o /cache/layers.tar ${IMAGE_NAME}

      - save_cache:
          key: cache-{{ .Branch }}-{{ epoch }}
          paths:
            - /cache/layers.tar

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
